### ISSUE TITLE
KeyError: 'gt_ref_obj_ix_frame_data'

### ISSUE THREAD

**Issue by wheltz** [ThierryDeruyttere/Talk2Car-Destination#8]
When I ran the test file of PDPC baseline, the `KeyError: 'gt_ref_obj_ix_frame_data'` error occurred in line260
```            
gt_ref_index = item["gt_ref_obj_ix_frame_data"]
```
And I did not find the keyword `gt_ref_obj_ix_frame_data` in other files. I think there is probably some problem with the json in the data folder. I did not find the ground truth of the reference object in it.

**Comment by ThierryDeruyttere** [comment]
Hi wheltz,

You are correct. I had prepared the files with this a week ago but didn't had the time yet to update them.
Here is the download link: https://drive.google.com/file/d/1xNECDDTEDA2rV0lkHhPDsUHG7OvO4aFs/view?usp=sharing
Also updated the readme.

Thanks!

**Comment by ThierryDeruyttere** [comment]
Make also sure that you have the frame data that was added to the readme about a week ago if you want to make drawings.

**Comment by wheltz** [comment]
Thank you so much! By the way, can you provide the code that generates the top-down view image(120 × 80) in the dataset? I may need to make some modifications to this part of the code to match my code.

**Comment by ThierryDeruyttere** [comment]
Hi, 

Have a look at https://github.com/ThierryDeruyttere/Talk2Car-Destination/tree/master/dataset_creation.
I've added the annotation tool that is provided as-is to show you how we did the mturk annotations. 
It won't run because some urls in the jsons lead to files that were removed but you should actually have all of the required files already in this repository. Currently, I do not have the intention or time to make this work out of the box.
I have also provided the script to rotate the top-down images. This will require you to download the Talk2Car dataset and the nuScenes dataset. 
Finally, I also provided a script to rotate the data from the original talk2car dataset, which you can run as-is (after downloading some more files).

**Comment by wheltz** [comment]
I deeply appreciate it, this is very helpful to me

**Comment by ThierryDeruyttere** [comment]
No worries, if you need more help let me know!
